// Code generated by github.com/primandproper/primitives-go/v2/config/envvars. DO NOT EDIT.

package envvars

const (
	// ObservabilityLoggingLevelEnvVarKey is the environment variable name to set to override
	// `Config.Observability.Logging.Level`.
	ObservabilityLoggingLevelEnvVarKey = "TEMPLATE_GO_OBSERVABILITY_LOGGING_LEVEL"

	// ObservabilityLoggingOtelSlogEndpointURLEnvVarKey is the environment variable name to set to
	// override `Config.Observability.Logging.OtelSlog.CollectorEndpoint`.
	ObservabilityLoggingOtelSlogEndpointURLEnvVarKey = "TEMPLATE_GO_OBSERVABILITY_LOGGING_OTEL_SLOG_ENDPOINT_URL"

	// ObservabilityLoggingOtelSlogInsecureEnvVarKey is the environment variable name to set to
	// override `Config.Observability.Logging.OtelSlog.Insecure`.
	ObservabilityLoggingOtelSlogInsecureEnvVarKey = "TEMPLATE_GO_OBSERVABILITY_LOGGING_OTEL_SLOG_INSECURE"

	// ObservabilityLoggingOtelSlogTimeoutEnvVarKey is the environment variable name to set to
	// override `Config.Observability.Logging.OtelSlog.Timeout`.
	ObservabilityLoggingOtelSlogTimeoutEnvVarKey = "TEMPLATE_GO_OBSERVABILITY_LOGGING_OTEL_SLOG_TIMEOUT"

	// ObservabilityLoggingProviderEnvVarKey is the environment variable name to set to override
	// `Config.Observability.Logging.Provider`.
	ObservabilityLoggingProviderEnvVarKey = "TEMPLATE_GO_OBSERVABILITY_LOGGING_PROVIDER"

	// ObservabilityLoggingServiceNameEnvVarKey is the environment variable name to set to override
	// `Config.Observability.Logging.ServiceName`.
	ObservabilityLoggingServiceNameEnvVarKey = "TEMPLATE_GO_OBSERVABILITY_LOGGING_SERVICE_NAME"

	// ObservabilityMetricsEnabledEnvVarKey is the environment variable name to set to override
	// `Config.Observability.Metrics.Enabled`.
	ObservabilityMetricsEnabledEnvVarKey = "TEMPLATE_GO_OBSERVABILITY_METRICS_ENABLED"

	// ObservabilityMetricsOtelCollectionIntervalEnvVarKey is the environment variable name to set
	// to override `Config.Observability.Metrics.Otel.CollectionInterval`.
	ObservabilityMetricsOtelCollectionIntervalEnvVarKey = "TEMPLATE_GO_OBSERVABILITY_METRICS_OTEL_COLLECTION_INTERVAL"

	// ObservabilityMetricsOtelCollectorEndpointEnvVarKey is the environment variable name to set
	// to override `Config.Observability.Metrics.Otel.CollectorEndpoint`.
	ObservabilityMetricsOtelCollectorEndpointEnvVarKey = "TEMPLATE_GO_OBSERVABILITY_METRICS_OTEL_COLLECTOR_ENDPOINT"

	// ObservabilityMetricsOtelEnableHostMetricsEnvVarKey is the environment variable name to set
	// to override `Config.Observability.Metrics.Otel.EnableHostMetrics`.
	ObservabilityMetricsOtelEnableHostMetricsEnvVarKey = "TEMPLATE_GO_OBSERVABILITY_METRICS_OTEL_ENABLE_HOST_METRICS"

	// ObservabilityMetricsOtelEnableRuntimeMetricsEnvVarKey is the environment variable name to
	// set to override `Config.Observability.Metrics.Otel.EnableRuntimeMetrics`.
	ObservabilityMetricsOtelEnableRuntimeMetricsEnvVarKey = "TEMPLATE_GO_OBSERVABILITY_METRICS_OTEL_ENABLE_RUNTIME_METRICS"

	// ObservabilityMetricsOtelInsecureEnvVarKey is the environment variable name to set to
	// override `Config.Observability.Metrics.Otel.Insecure`.
	ObservabilityMetricsOtelInsecureEnvVarKey = "TEMPLATE_GO_OBSERVABILITY_METRICS_OTEL_INSECURE"

	// ObservabilityMetricsProviderEnvVarKey is the environment variable name to set to override
	// `Config.Observability.Metrics.Provider`.
	ObservabilityMetricsProviderEnvVarKey = "TEMPLATE_GO_OBSERVABILITY_METRICS_PROVIDER"

	// ObservabilityMetricsServiceNameEnvVarKey is the environment variable name to set to override
	// `Config.Observability.Metrics.ServiceName`.
	ObservabilityMetricsServiceNameEnvVarKey = "TEMPLATE_GO_OBSERVABILITY_METRICS_SERVICE_NAME"

	// ObservabilityProfilingPprofEnableBlockProfileEnvVarKey is the environment variable name to
	// set to override `Config.Observability.Profiling.Pprof.EnableBlockProfile`.
	ObservabilityProfilingPprofEnableBlockProfileEnvVarKey = "TEMPLATE_GO_OBSERVABILITY_PROFILING_PPROF_ENABLE_BLOCK_PROFILE"

	// ObservabilityProfilingPprofEnableMutexProfileEnvVarKey is the environment variable name to
	// set to override `Config.Observability.Profiling.Pprof.EnableMutexProfile`.
	ObservabilityProfilingPprofEnableMutexProfileEnvVarKey = "TEMPLATE_GO_OBSERVABILITY_PROFILING_PPROF_ENABLE_MUTEX_PROFILE"

	// ObservabilityProfilingPprofPortEnvVarKey is the environment variable name to set to override
	// `Config.Observability.Profiling.Pprof.Port`.
	ObservabilityProfilingPprofPortEnvVarKey = "TEMPLATE_GO_OBSERVABILITY_PROFILING_PPROF_PORT"

	// ObservabilityProfilingProviderEnvVarKey is the environment variable name to set to override
	// `Config.Observability.Profiling.Provider`.
	ObservabilityProfilingProviderEnvVarKey = "TEMPLATE_GO_OBSERVABILITY_PROFILING_PROVIDER"

	// ObservabilityProfilingPyroscopeBasicAuthPasswordEnvVarKey is the environment variable name
	// to set to override `Config.Observability.Profiling.Pyroscope.BasicAuthPassword`.
	ObservabilityProfilingPyroscopeBasicAuthPasswordEnvVarKey = "TEMPLATE_GO_OBSERVABILITY_PROFILING_PYROSCOPE_BASIC_AUTH_PASSWORD"

	// ObservabilityProfilingPyroscopeBasicAuthUserEnvVarKey is the environment variable name to
	// set to override `Config.Observability.Profiling.Pyroscope.BasicAuthUser`.
	ObservabilityProfilingPyroscopeBasicAuthUserEnvVarKey = "TEMPLATE_GO_OBSERVABILITY_PROFILING_PYROSCOPE_BASIC_AUTH_USER"

	// ObservabilityProfilingPyroscopeEnableBlockProfileEnvVarKey is the environment variable name
	// to set to override `Config.Observability.Profiling.Pyroscope.EnableBlockProfile`.
	ObservabilityProfilingPyroscopeEnableBlockProfileEnvVarKey = "TEMPLATE_GO_OBSERVABILITY_PROFILING_PYROSCOPE_ENABLE_BLOCK_PROFILE"

	// ObservabilityProfilingPyroscopeEnableMutexProfileEnvVarKey is the environment variable name
	// to set to override `Config.Observability.Profiling.Pyroscope.EnableMutexProfile`.
	ObservabilityProfilingPyroscopeEnableMutexProfileEnvVarKey = "TEMPLATE_GO_OBSERVABILITY_PROFILING_PYROSCOPE_ENABLE_MUTEX_PROFILE"

	// ObservabilityProfilingPyroscopeInsecureEnvVarKey is the environment variable name to set to
	// override `Config.Observability.Profiling.Pyroscope.Insecure`.
	ObservabilityProfilingPyroscopeInsecureEnvVarKey = "TEMPLATE_GO_OBSERVABILITY_PROFILING_PYROSCOPE_INSECURE"

	// ObservabilityProfilingPyroscopeServerAddressEnvVarKey is the environment variable name to
	// set to override `Config.Observability.Profiling.Pyroscope.ServerAddress`.
	ObservabilityProfilingPyroscopeServerAddressEnvVarKey = "TEMPLATE_GO_OBSERVABILITY_PROFILING_PYROSCOPE_SERVER_ADDRESS"

	// ObservabilityProfilingPyroscopeUploadRateEnvVarKey is the environment variable name to set
	// to override `Config.Observability.Profiling.Pyroscope.UploadRate`.
	ObservabilityProfilingPyroscopeUploadRateEnvVarKey = "TEMPLATE_GO_OBSERVABILITY_PROFILING_PYROSCOPE_UPLOAD_RATE"

	// ObservabilityProfilingServiceNameEnvVarKey is the environment variable name to set to
	// override `Config.Observability.Profiling.ServiceName`.
	ObservabilityProfilingServiceNameEnvVarKey = "TEMPLATE_GO_OBSERVABILITY_PROFILING_SERVICE_NAME"

	// ObservabilityTracingCloudtraceGoogleCloudTraceProjectIDEnvVarKey is the environment variable
	// name to set to override `Config.Observability.Tracing.CloudTrace.ProjectID`.
	ObservabilityTracingCloudtraceGoogleCloudTraceProjectIDEnvVarKey = "TEMPLATE_GO_OBSERVABILITY_TRACING_CLOUDTRACE_GOOGLE_CLOUD_TRACE_PROJECT_ID"

	// ObservabilityTracingOtelgrpcCollectorEndpointEnvVarKey is the environment variable name to
	// set to override `Config.Observability.Tracing.Otel.CollectorEndpoint`.
	ObservabilityTracingOtelgrpcCollectorEndpointEnvVarKey = "TEMPLATE_GO_OBSERVABILITY_TRACING_OTELGRPC_COLLECTOR_ENDPOINT"

	// ObservabilityTracingOtelgrpcInsecureEnvVarKey is the environment variable name to set to
	// override `Config.Observability.Tracing.Otel.Insecure`.
	ObservabilityTracingOtelgrpcInsecureEnvVarKey = "TEMPLATE_GO_OBSERVABILITY_TRACING_OTELGRPC_INSECURE"

	// ObservabilityTracingProviderEnvVarKey is the environment variable name to set to override
	// `Config.Observability.Tracing.Provider`.
	ObservabilityTracingProviderEnvVarKey = "TEMPLATE_GO_OBSERVABILITY_TRACING_PROVIDER"

	// ObservabilityTracingServiceNameEnvVarKey is the environment variable name to set to override
	// `Config.Observability.Tracing.ServiceName`.
	ObservabilityTracingServiceNameEnvVarKey = "TEMPLATE_GO_OBSERVABILITY_TRACING_SERVICE_NAME"

	// ObservabilityTracingSpanCollectionProbabilityEnvVarKey is the environment variable name to
	// set to override `Config.Observability.Tracing.SpanCollectionProbability`.
	ObservabilityTracingSpanCollectionProbabilityEnvVarKey = "TEMPLATE_GO_OBSERVABILITY_TRACING_SPAN_COLLECTION_PROBABILITY"
)
